### ISSUE TITLE
How to import all the components.

### ISSUE THREAD

**Issue by ricardo17coelho** [menteora/vuetify-extra#3]
Hi friend, 
This is a very good project. Is exactly what i'm looking for.
Can you please tell me how you import the library into an other project ? And how to use the components?

It's possible to create a lib just for 1 components ?

I saw a lot of samples, but without vuetify.

thank you very much!

**Comment by menteora** [comment]
Hi @ricardo17coelho,

> Can you please tell me how you import the library into an other project ? And how to use the components?

Yes, you must install vuetify library and my library with `npm` and then import my library after vuetify inside `main.js` like this:

```javascript

import Vue from 'vue'
import Vuetify from 'vuetify/lib'
import VuetifyExtra from '@menteora/vuetify-extra'

Vue.use(Vuetify)
Vue.use(VuetifyExtra)

var vuetify =  new Vuetify({
  icons: {
    iconfont: 'mdi'
  }
})

new Vue({
  vuetify,
  render: h => h(App)
}).$mount('#app')
```

for a more elegant solution see my  `dev` folder that uses `plugins` folder, see [main.js](https://github.com/menteora/vuetify-extra/blob/master/dev/main.js)

If you want understand how to use the components see [App.vue](https://github.com/menteora/vuetify-extra/blob/master/dev/App.vue)

I will update the readme.

> It's possible to create a lib just for 1 components ?

Yes, it's possible, in my library I create one component for every files contained in `components` folder (see [components folder](https://github.com/menteora/vuetify-extra/tree/master/src/components)), you can put only one component inside components folder for example.

> I saw a lot of samples, but without vuetify.
>
> thank you very much!

Thank you, I also had the same initial problem. I hope can help you.
