### ISSUE TITLE
Error by importing lib

### ISSUE THREAD

**Issue by ricardo17coelho** [menteora/vuetify-extra#4]
running this commands: 

1. `npm install`
2. `npm run build`

On my project:

`npm install /path/to/vuetify-extra.git` 

> src/plugins/vuetify-extra.js

`import Vue from 'vue';`
`import VuetifyExtra from "@menteora/vuetify-extra";`
`Vue.use(VuetifyExtra);`

> src/main.js

`import vuetify  from "./plugins/vuetify";
import "./plugins/vuetify-extra";`

after that:

running my project with 
`npm run serve`

and get this error:

>  warning  in ./src/plugins/vuetify-extra-components.js

> "export 'default' (imported as 'VuetifyExtra') was not found in '@menteora/vuetify-extra'

Do you know this error? Or do you know what i'm doing wrong?

Thx!

**Comment by menteora** [comment]
Hi @ricardo17coelho, I've only one doubt:

> On my project:
> 
> `npm install /path/to/vuetify-extra.git`

Have you tried `npm install @menteora/vuetify-extra` ?

L.

**Comment by ricardo17coelho** [comment]
Hi @menteora ,

No, i'm not. 
But is possible to install it local or not ?

**Comment by menteora** [comment]
**Yes,** I've lost a lot of hours to find correct way to do this. :sweat_smile:

Use `npm run build:local`

On package.json uses `npm pack` under the hood:
```
"build:local": "vue-cli-service build --target lib --name menteora src/plugin.js && npm pack",
```
and in your project use: 
```
npm install /path/to/<libraryname>-<version>.tgz
```
**NOTE:** Not use `npm link` for this purpose, creates a lot of strange errors based on dependencies. :dizzy_face:

**Comment by ricardo17coelho** [comment]
`npm install /path/to/<libraryname>-<version>.tgz`

this method works, but own css into the components (code is into the generated css file) was not imported.

> 

>

**Comment by menteora** [comment]
I use vuetify css.

You can use loader, see quickstart : https://vuetifyjs.com/en/getting-started/quick-start

Or import manually:
```
import Vuetify from 'vuetify'
import 'vuetify/dist/vuetify.min.css'
```

**Comment by ricardo17coelho** [comment]
i mean own css from components. Not css from VUETIFY.

i have created a project with

`vue create myProject`

and than:

`vue add vuetify`

That means that vuetify is already global installed/imported and i don't need to import Vuetify css
but myComponent CSS was no imported into the project.

**Comment by menteora** [comment]
Sorry, but my project work with Vuetify css, I've not tested with custom css, It's not my target at the moment.

If you want import your custom css I think you can `import '@menteora/vuetify-extra/dist/menteora.css'` (follow the path of css inside `node_module`)
